os: osx
language: objective-c
osx_image: xcode10
xcode_workspace: ShadowsocksX-NG.xcworkspace
xcode_scheme: ShadowsocksX-NG
script:
  - mkdir /tmp
  - set -o pipefail
  - xcodebuild -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG -configuration Debug clean build CONFIGURATION_BUILD_DIR=/tmp/
  - cd /tmp && ls
