language: objective-c
osx_image: xcode12
xcode_workspace: ShadowsocksX-NG.xcworkspace
xcode_scheme: ShadowsocksX-NG

install:
  - pod install

script:
  - set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
